apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-dp
  labels:
    app: portal-noticias-dp
spec:
  template:
    metadata:
      labels:
        app: portal-noticias
    spec:
      containers:
      - name: portal
        image: aluracursos/portal-noticias:1
        ports:
          - containerPort: 80
        envFrom:
          - configMapRef:
              name: portal-configmap
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias