apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  selector:
    app: sistema-noticias
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort