apiVersion: v1
kind: Service
metadata:
  name: svc-portal-noticias
spec:
  selector:
    app: portal-noticias
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort